[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  version = "1.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.5.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "*"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/configor"
