<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: price.proto

namespace Flight\Price;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flight.price.CityCheapestPriceRequest</code>
 */
class CityCheapestPriceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 DepartureCityID = 1;</code>
     */
    private $DepartureCityID = 0;
    /**
     * Generated from protobuf field <code>uint64 ArriveCityID = 2;</code>
     */
    private $ArriveCityID = 0;

    public function __construct() {
        \GPBMetadata\Price::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 DepartureCityID = 1;</code>
     * @return int|string
     */
    public function getDepartureCityID()
    {
        return $this->DepartureCityID;
    }

    /**
     * Generated from protobuf field <code>uint64 DepartureCityID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDepartureCityID($var)
    {
        GPBUtil::checkUint64($var);
        $this->DepartureCityID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 ArriveCityID = 2;</code>
     * @return int|string
     */
    public function getArriveCityID()
    {
        return $this->ArriveCityID;
    }

    /**
     * Generated from protobuf field <code>uint64 ArriveCityID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setArriveCityID($var)
    {
        GPBUtil::checkUint64($var);
        $this->ArriveCityID = $var;

        return $this;
    }

}

