<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: price.proto

namespace Flight\Price;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flight.price.CityCheapestPriceReply</code>
 */
class CityCheapestPriceReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 DepartureCityID = 1;</code>
     */
    private $DepartureCityID = 0;
    /**
     * Generated from protobuf field <code>uint64 ArriveCityID = 2;</code>
     */
    private $ArriveCityID = 0;
    /**
     * Generated from protobuf field <code>float Price = 3;</code>
     */
    private $Price = 0.0;
    /**
     * Generated from protobuf field <code>string Concurrency = 4;</code>
     */
    private $Concurrency = '';

    public function __construct() {
        \GPBMetadata\Price::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 DepartureCityID = 1;</code>
     * @return int|string
     */
    public function getDepartureCityID()
    {
        return $this->DepartureCityID;
    }

    /**
     * Generated from protobuf field <code>uint64 DepartureCityID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDepartureCityID($var)
    {
        GPBUtil::checkUint64($var);
        $this->DepartureCityID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 ArriveCityID = 2;</code>
     * @return int|string
     */
    public function getArriveCityID()
    {
        return $this->ArriveCityID;
    }

    /**
     * Generated from protobuf field <code>uint64 ArriveCityID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setArriveCityID($var)
    {
        GPBUtil::checkUint64($var);
        $this->ArriveCityID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Price = 3;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->Price;
    }

    /**
     * Generated from protobuf field <code>float Price = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->Price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Concurrency = 4;</code>
     * @return string
     */
    public function getConcurrency()
    {
        return $this->Concurrency;
    }

    /**
     * Generated from protobuf field <code>string Concurrency = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setConcurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->Concurrency = $var;

        return $this;
    }

}

