<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: price.proto

namespace GPBMetadata;

class Price
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0adb010a0b70726963652e70726f746f120c666c696768742e7072696365" .
            "22490a184369747943686561706573745072696365526571756573741217" .
            "0a0f44657061727475726543697479494418012001280412140a0c417272" .
            "697665436974794944180220012804226b0a164369747943686561706573" .
            "7450726963655265706c7912170a0f446570617274757265436974794944" .
            "18012001280412140a0c417272697665436974794944180220012804120d" .
            "0a05507269636518032001280212130a0b436f6e63757272656e63791804" .
            "20012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

