<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Price::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a94010a0d736572766963652e70726f746f120c666c696768742e707269" .
            "6365326d0a05507269636512640a14476574436974794368656170657374" .
            "507269636512262e666c696768742e70726963652e436974794368656170" .
            "6573745072696365526571756573741a242e666c696768742e7072696365" .
            "2e43697479436865617065737450726963655265706c79620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

