// Code generated by protoc-gen-go. DO NOT EDIT.
// source: price.proto

package flight_price

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CityCheapestPriceRequest struct {
	DepartureCityID      uint64   `protobuf:"varint,1,opt,name=DepartureCityID" json:"DepartureCityID,omitempty"`
	ArriveCityID         uint64   `protobuf:"varint,2,opt,name=ArriveCityID" json:"ArriveCityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityCheapestPriceRequest) Reset()         { *m = CityCheapestPriceRequest{} }
func (m *CityCheapestPriceRequest) String() string { return proto.CompactTextString(m) }
func (*CityCheapestPriceRequest) ProtoMessage()    {}
func (*CityCheapestPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_price_67365ab34dce573b, []int{0}
}
func (m *CityCheapestPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityCheapestPriceRequest.Unmarshal(m, b)
}
func (m *CityCheapestPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityCheapestPriceRequest.Marshal(b, m, deterministic)
}
func (dst *CityCheapestPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityCheapestPriceRequest.Merge(dst, src)
}
func (m *CityCheapestPriceRequest) XXX_Size() int {
	return xxx_messageInfo_CityCheapestPriceRequest.Size(m)
}
func (m *CityCheapestPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CityCheapestPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CityCheapestPriceRequest proto.InternalMessageInfo

func (m *CityCheapestPriceRequest) GetDepartureCityID() uint64 {
	if m != nil {
		return m.DepartureCityID
	}
	return 0
}

func (m *CityCheapestPriceRequest) GetArriveCityID() uint64 {
	if m != nil {
		return m.ArriveCityID
	}
	return 0
}

type CityCheapestPriceReply struct {
	DepartureCityID      uint64   `protobuf:"varint,1,opt,name=DepartureCityID" json:"DepartureCityID,omitempty"`
	ArriveCityID         uint64   `protobuf:"varint,2,opt,name=ArriveCityID" json:"ArriveCityID,omitempty"`
	Price                float32  `protobuf:"fixed32,3,opt,name=Price" json:"Price,omitempty"`
	Concurrency          string   `protobuf:"bytes,4,opt,name=Concurrency" json:"Concurrency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityCheapestPriceReply) Reset()         { *m = CityCheapestPriceReply{} }
func (m *CityCheapestPriceReply) String() string { return proto.CompactTextString(m) }
func (*CityCheapestPriceReply) ProtoMessage()    {}
func (*CityCheapestPriceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_price_67365ab34dce573b, []int{1}
}
func (m *CityCheapestPriceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityCheapestPriceReply.Unmarshal(m, b)
}
func (m *CityCheapestPriceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityCheapestPriceReply.Marshal(b, m, deterministic)
}
func (dst *CityCheapestPriceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityCheapestPriceReply.Merge(dst, src)
}
func (m *CityCheapestPriceReply) XXX_Size() int {
	return xxx_messageInfo_CityCheapestPriceReply.Size(m)
}
func (m *CityCheapestPriceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CityCheapestPriceReply.DiscardUnknown(m)
}

var xxx_messageInfo_CityCheapestPriceReply proto.InternalMessageInfo

func (m *CityCheapestPriceReply) GetDepartureCityID() uint64 {
	if m != nil {
		return m.DepartureCityID
	}
	return 0
}

func (m *CityCheapestPriceReply) GetArriveCityID() uint64 {
	if m != nil {
		return m.ArriveCityID
	}
	return 0
}

func (m *CityCheapestPriceReply) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CityCheapestPriceReply) GetConcurrency() string {
	if m != nil {
		return m.Concurrency
	}
	return ""
}

func init() {
	proto.RegisterType((*CityCheapestPriceRequest)(nil), "flight.price.CityCheapestPriceRequest")
	proto.RegisterType((*CityCheapestPriceReply)(nil), "flight.price.CityCheapestPriceReply")
}

func init() { proto.RegisterFile("price.proto", fileDescriptor_price_67365ab34dce573b) }

var fileDescriptor_price_67365ab34dce573b = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0x4c,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x49, 0xcb, 0xc9, 0x4c, 0xcf, 0x28, 0xd1,
	0x03, 0x8b, 0x29, 0x65, 0x70, 0x49, 0x38, 0x67, 0x96, 0x54, 0x3a, 0x67, 0xa4, 0x26, 0x16, 0xa4,
	0x16, 0x97, 0x04, 0x80, 0x04, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x34, 0xb8, 0xf8,
	0x5d, 0x52, 0x0b, 0x12, 0x8b, 0x4a, 0x4a, 0x8b, 0x52, 0x41, 0x8a, 0x3c, 0x5d, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x58, 0x82, 0xd0, 0x85, 0x85, 0x94, 0xb8, 0x78, 0x1c, 0x8b, 0x8a, 0x32, 0xcb, 0x60,
	0xca, 0x98, 0xc0, 0xca, 0x50, 0xc4, 0x94, 0xe6, 0x31, 0x72, 0x89, 0x61, 0xb1, 0xaa, 0x20, 0xa7,
	0x92, 0xba, 0x16, 0x09, 0x89, 0x70, 0xb1, 0x82, 0xcd, 0x96, 0x60, 0x56, 0x60, 0xd4, 0x60, 0x0a,
	0x82, 0x70, 0x84, 0x14, 0xb8, 0xb8, 0x9d, 0xf3, 0xf3, 0x92, 0x4b, 0x8b, 0x8a, 0x52, 0xf3, 0x92,
	0x2b, 0x25, 0x58, 0x14, 0x18, 0x35, 0x38, 0x83, 0x90, 0x85, 0x92, 0xd8, 0xc0, 0xe1, 0x63, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xe0, 0xed, 0x56, 0x2e, 0x01, 0x00, 0x00,
}
